---
title: "Methods"
format: 
  pdf
execute:
  echo: false
  warning: false
jupyter: python3
---

# Methods documentation

In [1]:
from IPython.display import Markdown, display

from tb_macro.document import get_func_notes, build_fixed_params_table, build_prior_ranges_table
from tb_macro.acf import add_acf
from tb_macro.health_system import (
    add_detection,
    add_treatment_flows,
    compute_outcome_props,
    get_outcome_rates,
)
from tb_macro.demography import (
    add_ageing_flows,
    add_entry_births,
    add_replacement_deaths,
    inflate_oldest_death_rates,
    prepare_pop_data_for_entries,
)
from tb_macro.epi import (
    add_infection_flows,
    add_latency_flows,
    add_natural_history,
    add_seeding,
    get_base_model,
    get_latency_age_adj,
    infect_process,
    initialise_pops,
)
from tb_macro.calibration import (
    make_log_likelihood,
    get_latent_log_likelihood,
    get_notification_log_likelihood,
    get_death_log_likelihood,
    get_adult_pulm_prev,
    get_pulm_prev_log_likelihood,
    get_prev_decline_log_likelihood,
    get_infprop_log_likelihood,
)
from tb_macro.parameters import BASE_PARAMS, PARAM_BOUNDS

In [2]:
display(Markdown("## Demographic model constructiuon"))
display(Markdown("### Ageing"))
display(Markdown(get_func_notes(add_ageing_flows)))
display(Markdown("### Oldest age group mortality"))
display(Markdown(get_func_notes(inflate_oldest_death_rates)))
display(Markdown("### Background mortality"))
display(Markdown(get_func_notes(add_replacement_deaths)))
display(Markdown("### Construction of entry rates"))
display(Markdown(get_func_notes(prepare_pop_data_for_entries)))
display(Markdown("### Population growth"))
display(Markdown(get_func_notes(add_entry_births)))

display(Markdown("## Epidemiological model construction"))
display(Markdown("### Compartments and stratifications"))
display(Markdown(get_func_notes(get_base_model)))
display(Markdown("### Initial population"))
display(Markdown(get_func_notes(initialise_pops)))
display(Markdown("### Seeding"))
display(Markdown(get_func_notes(add_seeding)))
display(Markdown("### Force of infection"))
display(Markdown(get_func_notes(infect_process)))
display(Markdown("### Infection"))
display(Markdown(get_func_notes(add_infection_flows)))
display(Markdown("### Latency age bands"))
display(Markdown(get_func_notes(get_latency_age_adj)))
display(Markdown("### Latency"))
display(Markdown(get_func_notes(add_latency_flows)))
display(Markdown("### Natural history"))
display(Markdown(get_func_notes(add_natural_history)))
display(Markdown("### Detection"))
display(Markdown(get_func_notes(add_detection)))
display(Markdown("### Treatment outcome proportions"))
display(Markdown(get_func_notes(compute_outcome_props)))
display(Markdown("### Treatment outcome rates"))
display(Markdown(get_func_notes(get_outcome_rates)))
display(Markdown("### Treatment"))
display(Markdown(get_func_notes(add_treatment_flows)))
display(Markdown("### Active case finding"))
display(Markdown(get_func_notes(add_acf)))

display(Markdown("## Calibration"))
display(Markdown(get_func_notes(make_log_likelihood)))
display(Markdown("### Prevalence of infection"))
display(Markdown(get_func_notes(get_latent_log_likelihood)))
display(Markdown("### Notifications"))
display(Markdown(get_func_notes(get_notification_log_likelihood)))
display(Markdown("### Deaths"))
display(Markdown(get_func_notes(get_death_log_likelihood)))
display(Markdown("### Definition of prevalent disease"))
display(Markdown(get_func_notes(get_adult_pulm_prev)))
display(Markdown("### Prevalence of pulmonary disease"))
display(Markdown(get_func_notes(get_pulm_prev_log_likelihood)))
display(Markdown("### Decline in prevalence"))
display(Markdown(get_func_notes(get_prev_decline_log_likelihood)))
display(Markdown("### Infectiousness of prevalent disease"))
display(Markdown(get_func_notes(get_infprop_log_likelihood)))

## Demographic model constructiuon

### Ageing

The population is stratified into the age groups with lower bounds being
0, 3, 5, 10, 15, 18, 40, 65 years. People move from each group to the next at a
constant rate equal to the reciprocal of the group width, such that
the mean time spent in an age group matches its width in years.

The oldest group has no ageing outflow. Exit from this group
occurs only through death.

### Oldest age group mortality

The death rate in the oldest age group is multiplied by
2. In reality the hazard of death
rises with age, so the population in this open-ended group is
concentrated at its younger end, with only a thin tail at the
oldest ages. The rate taken from the data is the average
hazard weighted by that distribution.

The model applies a single constant hazard to the whole group,
which implies exponential attrition and a heavier old-age tail.
Without inflation, too many people remain in this group relative
to the reported age distribution.

### Background mortality

Background (non-TB-related) mortality is applied as
an age-specific per capita rate,
interpolated over calendar time from the
death rates provided.

Each death is immediately replaced by a birth into the
_Mtb_-naive youngest age group. This keeps background
mortality from affecting the population size,
while returning newborns without prior infection.

### Construction of entry rates

Entry rates are calculated as the year-to-year increments
in total population, after inserting the model's
starting population at the start of the simulation.

### Population growth

Additional births enter the _Mtb_-naive youngest age group.
The supplied entry rates are applied as a step function in
calendar time.

Together with replacement of background deaths, this
produces a population that tracks the external totals while
remaining fully naive at birth.
Note that this entry rate may reach negative values,
but these negative entries are then more than compensated for by
the death replacements as births.

## Epidemiological model construction

### Compartments and stratifications

All people within the simulation are assigned to one of the
following TB-related states: mtb_naive, incipient, contained, cleared, active, treatment, recovered.
These are stratified by age with lower bounds: 0, 3, 5, 10, 15, 18, 40, 65
years. Active TB is further stratified by infectiousness
(low, high) and by clinical status (subclinical or
clinical).

The model is solved at steps of 0.5 years.

### Initial population

The simulation begins with the entire population in the
_Mtb_-naive compartment, distributed across the age groups
with lower bounds 0, 3, 5, 10, 15, 18, 40, 65 according to the supplied
starting age distribution.

### Seeding

Infection is seeded from the _Mtb_-naive compartment into
incipient infection with a triangular pulse. The pulse peaks
at the "seeding peak year" at a rate of "seeding peak rate",
with width "seeding duration".

### Force of infection

The force of infection is age-specific. Age groups whose
lower bound is below the young-age cutoff do not contribute
to transmission, and have susceptibility reduced by the
"relative susceptibility of children".

Each infectious person is weighted by the
"relative infectiousness of low-infectious TB" if in the low infectiousness
stratum, and by the "relative infectiousness of subclinical TB" if
subclinical. The resulting age-specific infectious pressure
is applied through the mixing matrix.

### Infection

Infection moves people from each of the susceptible states
mtb_naive, contained, cleared, recovered into incipient infection.

The force of infection is scaled by the
"raw transmission rate" and by a relative susceptibility
that depends on the source state: "relative susceptibility of the never-infected"
for the never-infected, "relative susceptibility of contained infection" for
contained infection, and "relative susceptibility of cleared or recovered infection" for both
cleared and recovered infection.

A time-varying mixing matrix is built from the
"background mixing", "assortative mixing spread" and "parent-child mixing strength"
parameters.

### Latency age bands

Containment and progression rates are grouped into three
latency bands: under 5 years, 5 to under 15 years, and
15 years and over.

### Latency

From incipient infection, people may contain infection or
progress to active disease. Both rates vary by the latency
age bands, using the "containment rate under 5 years",
"containment rate ages 5 to 15" and "containment rate ages 15 and over"
for containment, and the "progression rate under 5 years",
"progression rate ages 5 to 15" and "progression rate ages 15 and over"
for progression.

Progression is to subclinical disease. A fraction given by
the "proportion of progressions that are high-infectious" enter the high
infectiousness stratum, and the remainder enter the low
infectiousness stratum.

### Natural history

After infection is contained, people may clear infection
or undergo endogenous reactivation (breakdown), at the
"clearance rate" and "breakdown rate" respectively.

Among people with active TB, infectiousness may increase or
decrease at the "rate of infectiousness increase" and
"rate of infectiousness decrease". Symptoms may develop or
resolve at the "rate of clinical progression" and
"rate of clinical regression".

Subclinical disease may self-resolve at the
"self-recovery rate". Untreated clinical TB causes death
at the "TB mortality rate for low-infectious disease" or
"TB mortality rate for high-infectious disease", according to infectiousness.
These deaths are replaced by _Mtb_-naive births into the
youngest age group.

### Active case finding

Active case finding screens people with active TB and transitions
detected cases into treatment. Unlike routine detection, this
includes subclinical disease.

The peak rate is given by $-\ln(1 - c) \times s$, where $c$ is
"active case finding coverage" and $s$ is "active case finding sensitivity".
This converts annual coverage into a hazard over time,
and then scales this rate by diagnostic sensitivity.

The rate is zero until the "active case finding start year", rises over
the course of "active case finding scale-up time" years
to its peak rate as defined above,
remains at the peak for the "active case finding duration",
and then returns to zero.

## Calibration

The log-likelihood is the sum of six contributions, taken as
independent: the prevalence of _Mtb_ infection, case notifications, TB
deaths, adult bacteriologically-confirmed prevalence, the decline in
prevalence between the two prevalence survey rounds,
and the proportion of prevalent disease that is highly infectious.

Two error models are applied throughout. Counts and ratios are compared
on the log scale, as
$\log \hat{y} \sim \mathcal{N}(\log y, \sigma_{c})$ with $\sigma_{c}$ of
0.1, so that the discrepancy scales with the magnitude of
the target. Proportions are compared on the log-odds scale, as
$\mathrm{logit}(\hat{p}) \sim \mathcal{N}(\mathrm{logit}(p), \sigma_{p})$
with $\sigma_{p}$ of 0.2, which respects their bounds at
zero and one. In both cases the transformed target provides the mean of
the distribution and the transformed modelled value is evaluated against
it, which is equivalent to the reverse for these symmetric
distributions.

Where a target spans multiple years, the log-density is averaged over
those years, so that each of the six contributions carries comparable
weight irrespective of how many observations it contains.

Parameter sets for which the solver does not reach a successful solution
are assigned a large negative log-likelihood, so that they are rejected
rather than contributing invalid model output to the likelihood.

### Prevalence of infection

The proportion of the population ever infected with _Mtb_ was compared
against the estimate from the tuberculin survey reported by Marks et al.
(Bulletin of the World Health Organization).

The modelled equivalent is everyone not previously infected with
_Mtb_, which is represented by all modelled compartments other than
_Mtb_ naive. That is, the incipient, contained, cleared, active, treatment, recovered states,
divided by the total population at the time of the survey.
All modelled age groups contributed to both the numerator and the denominator.

Being a proportion, this quantity was compared on the log-odds scale with
a standard deviation of 0.2.

### Notifications

Modelled case detections were compared against the notifications
obtained from the Vietnam National Tuberculosis Program. These are
reported by calendar year, and so are offset by
0.5 of a year to sit at mid-year in model time
(because we consider whole numbers of years in modelled time
to represent the starts and ends of years).

As counts, notifications are compared on the log scale with a
standard deviation of 0.1, which relates the difference
to the size of the target, rather than being absolute.
The log-density is averaged rather than summed over the years of data, so
that this multi-year series contributes comparable weight to the likelihood
as the single-point targets.

### Deaths

Modelled TB deaths are compared against the WHO estimates of TB
mortality for VNM. Deaths occurring in the community and during
treatment are summed before comparison, because the estimates do not
distinguish between them.

As for notifications, these counts are compared on the log scale with a
standard deviation of 0.1, and averaged over the years for
which estimates are available.

### Definition of prevalent disease

Prevalence is calculated to approximate the quantity ascertained by a
bacteriologically confirmed prevalence survey, and so is restricted to
adults, taken here as those aged 15 years and over.

Three groups contribute to the numerator: all those with active disease
in the high infectiousness stratum, a fraction of those in the low
infectiousness stratum given by the "proportion of low-infectious TB that is bacteriologically positive", and
everyone currently receiving treatment. Clinical status does not
enter this calculation, such that subclinical disease contributes
on the same basis as clinical disease.

The denominator is the total adult population at the same time point.

### Prevalence of pulmonary disease

Modelled adult prevalence of bacteriologically confirmed pulmonary TB was
compared against the second Vietnamese national prevalence survey
(PLOS One). The target is published per 100,000 population and converted
to a proportion of the adult population.

Being a proportion, this quantity was compared on the log-odds scale with
a standard deviation of 0.2.

### Decline in prevalence

The two survey rounds reported by Nguyen et al. (Emerging Infectious
Diseases) are used to target the decline in prevalence rather than absolute values.
Only the ratio of the later to the earlier estimate is taken,
so that the target constrains the trend in prevalence while remaining
insensitive to any discrepancy between the quantity these surveys
assess and our definition of prevalence.

The modelled ratio applies the same adult prevalence definition at both
time points. The ratio is strictly positive, so it is compared on the
log scale with a standard deviation of 0.1.

### Infectiousness of prevalent disease

The proportion of prevalent adult TB that is highly infectious was
compared against the equivalent proportion from the second Vietnamese
national prevalence survey.

The numerator is the high infectiousness stratum of the active
compartment and the denominator is total adult prevalence, as defined
above. This target therefore constrains how prevalent disease is
distributed across the infectiousness strata, without further
constraining the overall size of the prevalent pool.

As a proportion, this quantity is compared on the log-odds scale with
a standard deviation of 0.2.

## Fixed parameters

In [3]:
fixed_params = {k: v for k, v in BASE_PARAMS.items() if k not in PARAM_BOUNDS}
build_fixed_params_table(fixed_params)

                                                       value
Parameter
relative susceptibility of the never-infected              1
relative infectiousness of subclinical TB                0.5
relative infectiousness of low-infectious TB             0.4
progression rate under 5 years                           2.4
progression rate ages 5 to 15                              2
progression rate ages 15 and over                        0.1
proportion of progressions that are high-infect...       0.5
containment rate under 5 years                           4.4
containment rate ages 5 to 15                            4.4
containment rate ages 15 and over                          2
rate of clinical regression                                1
rate of infectiousness decrease                            1
TB mortality rate for high-infectious disease          0.389
TB mortality rate for low-infectious disease           0.025
self-recovery rate                                       0.4
rx_duration                                              0.5
seeding peak year                                       1830
seeding duration                                          10
seeding peak rate                                       0.01
active case finding coverage                               0
active case finding sensitivity                            0
active case finding start year                          2027
active case finding duration                               5
active case finding scale-up time                          1
proportion of low-infectious TB that is bacteri...  0.666667

## Prior ranges

Pass the dict of prior bounds to show.

In [4]:
build_prior_ranges_table(PARAM_BOUNDS)

                                                    lower upper
Parameter
raw transmission rate                                  12    20
background mixing                                   0.002  0.04
assortative mixing spread                               5    15
parent-child mixing strength                            1   2.5
relative susceptibility of contained infection        0.2   0.6
relative susceptibility of cleared or recovered...    0.5     1
relative susceptibility of children                   0.5     1
breakdown rate                                       0.01     1
clearance rate                                       0.01   0.1
rate of clinical progression                         0.25     2
rate of infectiousness increase                      0.25     2
detect_rate_current                                   0.5   1.5
rel_detect_2010                                       0.5     1
rel_detect_1986                                      0.25  0.75