---
title: "Methods"
format: 
  pdf
execute:
  echo: false
  warning: false
jupyter: python3
---

# Methods documentation

In [1]:
from IPython.display import Markdown, display

from tb_macro.document import get_func_notes, build_fixed_params_table, build_prior_ranges_table
from tb_macro.acf import add_acf
from tb_macro.health_system import (
    add_detection,
    add_treatment_flows,
    compute_outcome_props,
    get_outcome_rates,
)
from tb_macro.inputs import (
    add_groups_to_single_pop,
    build_age_weight_lookup,
    calc_death_in_unsucc_outcomes,
    calc_tsr_from_outcomes,
    convert_conmat,
    get_country_indicators,
    get_country_pop,
    get_fertility_data,
    get_single_age_pop_from_ungroups,
    get_un_mortality,
    load_demography,
    load_fertility,
    load_who_outcomes,
)
from tb_macro.mixing import (
    aggregate_full_matrix_to_groups,
    build_c_matrix,
    build_s_matrix,
    build_s_matrix_single_age,
    get_full_normalised_within_age_band_weights,
    get_norm_c_matrix,
)
from tb_macro.demography import (
    add_ageing_flows,
    add_entry_births,
    add_replacement_deaths,
    inflate_oldest_death_rates,
    prepare_pop_data_for_entries,
)
from tb_macro.epi import (
    add_infection_flows,
    add_latency_flows,
    add_natural_history,
    add_seeding,
    get_base_model,
    get_latency_age_adj,
    infect_process,
    initialise_pops,
)
from tb_macro.calibration import (
    make_log_likelihood,
    get_latent_log_likelihood,
    get_notification_log_likelihood,
    get_death_log_likelihood,
    get_adult_pulm_prev,
    get_pulm_prev_log_likelihood,
    get_prev_decline_log_likelihood,
    get_infprop_log_likelihood,
)
from tb_macro.outputs import (
    build_age_mapping,
    get_age_clin_prev,
    get_age_deaths,
    get_age_inc,
    get_age_latent,
    get_age_notifs,
    get_age_prev,
    get_age_pulm_prev,
    get_age_recovered_prev,
    get_age_rx_prev,
    map_and_regroup_output,
    regroup_full_outputs,
)
from tb_macro.parameters import BASE_PARAMS, PARAM_BOUNDS

In [9]:
display(Markdown("""## Demographic structure
The modelled population is stratified by age. 
Our demographic model is designed to exactly match total population size estimates,
be mechanistically coherent and to support a realistic population distribution by age 
to emerge from the applied demographic processes.
"""))
display(Markdown(get_func_notes(add_ageing_flows)))

display(Markdown("""### Population data"""))
display(Markdown(
    get_func_notes(get_country_pop) + " " +
    get_func_notes(get_single_age_pop_from_ungroups) +
    """ This approach allows the population to then be
    aggregated to any requested set of age groups.
    """
    )
)
display(Markdown("""### Background mortality

Age-specific death rates are formed from UN deaths and population in each modelled age group. The open-ended oldest group is adjusted, then non-TB deaths are applied as replacement births into the uninfected youngest group.
"""))
display(Markdown(get_func_notes(get_un_mortality)))
display(Markdown(get_func_notes(load_demography)))
display(Markdown(get_func_notes(inflate_oldest_death_rates)))
display(Markdown(get_func_notes(add_replacement_deaths)))

display(Markdown("""### Population size

Replacement of deaths keeps background mortality from changing the total population. Extra entries, which may be negative, then match the UN totals. The run starts with the whole population uninfected.
"""))
display(Markdown(get_func_notes(prepare_pop_data_for_entries)))
display(Markdown(get_func_notes(add_entry_births)))
display(Markdown(get_func_notes(initialise_pops)))

display(Markdown("""## Natural history of tuberculosis

People occupy a small set of TB-related states, further split by age and, for active disease, by infectiousness and symptoms. Infection is seeded historically, then maintained by transmission.
"""))
display(Markdown(get_func_notes(get_base_model)))
display(Markdown(get_func_notes(add_seeding)))

display(Markdown("""### Infection

Infection moves susceptible people into incipient infection. The force of infection is age-specific and uses the mixing matrix described below.
"""))
display(Markdown(get_func_notes(add_infection_flows)))
display(Markdown(get_func_notes(infect_process)))

display(Markdown("""### Latency and progression

From incipient infection, people may contain infection or progress to active disease. Both rates vary by age.
"""))
display(Markdown(get_func_notes(get_latency_age_adj)))
display(Markdown(get_func_notes(add_latency_flows)))

display(Markdown("""### Active disease
"""))
display(Markdown(get_func_notes(add_natural_history)))

display(Markdown("""### Detection and treatment

Routine detection applies only to clinical disease. Treatment outcomes are derived from the success rate and the share of unsuccessful outcomes that are deaths, after allowing for background mortality during a course of treatment. Active case finding is a later, optional process and includes subclinical disease.
"""))
display(Markdown(get_func_notes(add_detection)))
display(Markdown(get_func_notes(compute_outcome_props)))
display(Markdown(get_func_notes(add_treatment_flows)))
display(Markdown(get_func_notes(add_acf)))

display(Markdown("## Population mixing"))
display(Markdown("### Age weights for mixing"))
display(Markdown(get_func_notes(build_age_weight_lookup)))
display(Markdown("### Fertility"))
display(Markdown(get_func_notes(get_fertility_data)))
display(Markdown(get_func_notes(load_fertility)))
display(Markdown("### Mixing kernel"))
display(Markdown(get_func_notes(build_s_matrix_single_age)))
display(Markdown("### Within-group age weights"))
display(Markdown(get_func_notes(get_full_normalised_within_age_band_weights)))
display(Markdown("### Aggregation to age groups"))
display(Markdown(get_func_notes(aggregate_full_matrix_to_groups)))
display(Markdown("### Group mixing"))
display(Markdown(get_func_notes(build_s_matrix)))
display(Markdown("### Population-scaled contacts"))
display(Markdown(get_func_notes(build_c_matrix)))
display(Markdown("### Mixing matrix normalisation"))
display(Markdown(get_func_notes(get_norm_c_matrix)))

display(Markdown("## Programmatic outcomes"))
display(Markdown("### Treatment success"))
display(Markdown(get_func_notes(calc_tsr_from_outcomes)))
display(Markdown("### Deaths among unsuccessful treatment"))
display(Markdown(get_func_notes(calc_death_in_unsucc_outcomes)))
display(Markdown("### WHO TB mortality"))
display(Markdown(get_func_notes(get_country_indicators)))
display(Markdown(get_func_notes(load_who_outcomes)))

display(Markdown("## Outputs"))
display(Markdown("### Incidence"))
display(Markdown(get_func_notes(get_age_inc)))
display(Markdown("### Prevalence"))
display(Markdown(get_func_notes(get_age_prev)))
display(Markdown("### Pulmonary prevalence"))
display(Markdown(get_func_notes(get_age_pulm_prev)))
display(Markdown("### Clinical prevalence"))
display(Markdown(get_func_notes(get_age_clin_prev)))
display(Markdown("### Treatment prevalence"))
display(Markdown(get_func_notes(get_age_rx_prev)))
display(Markdown("### Recovered"))
display(Markdown(get_func_notes(get_age_recovered_prev)))
display(Markdown("### Ever-infected"))
display(Markdown(get_func_notes(get_age_latent)))
display(Markdown("### Notifications"))
display(Markdown(get_func_notes(get_age_notifs)))
display(Markdown("### TB deaths"))
display(Markdown(get_func_notes(get_age_deaths)))
display(Markdown("### Mapping to output age groups"))
display(Markdown(get_func_notes(build_age_mapping)))
display(Markdown(get_func_notes(map_and_regroup_output)))
display(Markdown(get_func_notes(regroup_full_outputs)))

display(Markdown("## Calibration"))
display(Markdown(get_func_notes(make_log_likelihood)))
display(Markdown("### Prevalence of infection"))
display(Markdown(get_func_notes(get_latent_log_likelihood)))
display(Markdown("### Notifications"))
display(Markdown(get_func_notes(get_notification_log_likelihood)))
display(Markdown("### Deaths"))
display(Markdown(get_func_notes(get_death_log_likelihood)))
display(Markdown("### Definition of prevalent disease"))
display(Markdown(get_func_notes(get_adult_pulm_prev)))
display(Markdown("### Prevalence of pulmonary disease"))
display(Markdown(get_func_notes(get_pulm_prev_log_likelihood)))
display(Markdown("### Decline in prevalence"))
display(Markdown(get_func_notes(get_prev_decline_log_likelihood)))
display(Markdown("### Infectiousness of prevalent disease"))
display(Markdown(get_func_notes(get_infprop_log_likelihood)))
display(Markdown("### UN population"))
display(Markdown(get_func_notes(get_country_pop)))
display(Markdown(get_func_notes(get_single_age_pop_from_ungroups)))
display(Markdown("### Model age groups"))
display(Markdown(get_func_notes(add_groups_to_single_pop)))
display(Markdown("### UN mortality"))
display(Markdown(get_func_notes(get_un_mortality)))
display(Markdown("### Ageing"))
display(Markdown(get_func_notes(add_ageing_flows)))
display(Markdown("### Oldest age group mortality"))
display(Markdown(get_func_notes(inflate_oldest_death_rates)))
display(Markdown("### Background mortality"))
display(Markdown(get_func_notes(add_replacement_deaths)))
display(Markdown("### Construction of entry rates"))
display(Markdown(get_func_notes(prepare_pop_data_for_entries)))
display(Markdown("### Population growth"))
display(Markdown(get_func_notes(add_entry_births)))

display(Markdown("## Epidemiological model construction"))
display(Markdown("### Compartments and stratifications"))
display(Markdown(get_func_notes(get_base_model)))
display(Markdown("### Initial population"))
display(Markdown(get_func_notes(initialise_pops)))
display(Markdown("### Seeding"))
display(Markdown(get_func_notes(add_seeding)))
display(Markdown("### Force of infection"))
display(Markdown(get_func_notes(infect_process)))
display(Markdown("### Infection"))
display(Markdown(get_func_notes(add_infection_flows)))

display(Markdown("### Latency age bands"))
display(Markdown(get_func_notes(get_latency_age_adj)))
display(Markdown("### Latency"))
display(Markdown(get_func_notes(add_latency_flows)))
display(Markdown("### Natural history"))
display(Markdown(get_func_notes(add_natural_history)))
display(Markdown("### Detection"))
display(Markdown(get_func_notes(add_detection)))
display(Markdown("### Treatment outcome proportions"))
display(Markdown(get_func_notes(compute_outcome_props)))
display(Markdown("### Treatment outcome rates"))
display(Markdown(get_func_notes(get_outcome_rates)))
display(Markdown("### Treatment"))
display(Markdown(get_func_notes(add_treatment_flows)))
display(Markdown("### Active case finding"))
display(Markdown(get_func_notes(add_acf)))

display(Markdown("## Population mixing"))
display(Markdown("### Age weights for mixing"))
display(Markdown(get_func_notes(build_age_weight_lookup)))
display(Markdown("### Fertility"))
display(Markdown(get_func_notes(get_fertility_data)))
display(Markdown(get_func_notes(load_fertility)))
display(Markdown("### Mixing kernel"))
display(Markdown(get_func_notes(build_s_matrix_single_age)))
display(Markdown("### Within-group age weights"))
display(Markdown(get_func_notes(get_full_normalised_within_age_band_weights)))
display(Markdown("### Aggregation to age groups"))
display(Markdown(get_func_notes(aggregate_full_matrix_to_groups)))
display(Markdown("### Group mixing"))
display(Markdown(get_func_notes(build_s_matrix)))
display(Markdown("### Population-scaled contacts"))
display(Markdown(get_func_notes(build_c_matrix)))
display(Markdown("### Mixing matrix normalisation"))
display(Markdown(get_func_notes(get_norm_c_matrix)))

display(Markdown("## Programmatic outcomes"))
display(Markdown("### Treatment success"))
display(Markdown(get_func_notes(calc_tsr_from_outcomes)))
display(Markdown("### Deaths among unsuccessful treatment"))
display(Markdown(get_func_notes(calc_death_in_unsucc_outcomes)))
display(Markdown("### WHO TB mortality"))
display(Markdown(get_func_notes(get_country_indicators)))
display(Markdown(get_func_notes(load_who_outcomes)))

display(Markdown("## Outputs"))
display(Markdown("### Incidence"))
display(Markdown(get_func_notes(get_age_inc)))
display(Markdown("### Prevalence"))
display(Markdown(get_func_notes(get_age_prev)))
display(Markdown("### Pulmonary prevalence"))
display(Markdown(get_func_notes(get_age_pulm_prev)))
display(Markdown("### Clinical prevalence"))
display(Markdown(get_func_notes(get_age_clin_prev)))
display(Markdown("### Treatment prevalence"))
display(Markdown(get_func_notes(get_age_rx_prev)))
display(Markdown("### Recovered"))
display(Markdown(get_func_notes(get_age_recovered_prev)))
display(Markdown("### Ever-infected"))
display(Markdown(get_func_notes(get_age_latent)))
display(Markdown("### Notifications"))
display(Markdown(get_func_notes(get_age_notifs)))
display(Markdown("### TB deaths"))
display(Markdown(get_func_notes(get_age_deaths)))
display(Markdown("### Mapping to output age groups"))
display(Markdown(get_func_notes(build_age_mapping)))
display(Markdown(get_func_notes(map_and_regroup_output)))
display(Markdown(get_func_notes(regroup_full_outputs)))

display(Markdown("## Calibration"))
display(Markdown(get_func_notes(make_log_likelihood)))
display(Markdown("### Prevalence of infection"))
display(Markdown(get_func_notes(get_latent_log_likelihood)))
display(Markdown("### Notifications"))
display(Markdown(get_func_notes(get_notification_log_likelihood)))
display(Markdown("### Deaths"))
display(Markdown(get_func_notes(get_death_log_likelihood)))
display(Markdown("### Definition of prevalent disease"))
display(Markdown(get_func_notes(get_adult_pulm_prev)))
display(Markdown("### Prevalence of pulmonary disease"))
display(Markdown(get_func_notes(get_pulm_prev_log_likelihood)))
display(Markdown("### Decline in prevalence"))
display(Markdown(get_func_notes(get_prev_decline_log_likelihood)))
display(Markdown("### Infectiousness of prevalent disease"))
display(Markdown(get_func_notes(get_infprop_log_likelihood)))

## Demographic structure
The modelled population is stratified by age.
Our demographic model is designed to exactly match total population size estimates,
be mechanistically coherent and to support a realistic population distribution by age
to emerge from the applied demographic processes.

The population is stratified into age groups with lower bounds of:
0, 3, 5, 10, 15, 18, 40, 65 years. People move from each group to the next at a
constant rate equal to the reciprocal of the with of the group
they are exiting in years, such that the mean time spent in
each age group matches its width. The oldest group has
no ageing outflow. Exit from this group occurs only through death.

### Population data

Population counts are taken from the UN World Population
Prospects, by calendar year and age group, for country: VNM. UN age-group counts are recorded in thousands and are
distributed uniformly across the single years of age
contained by each group before further processing
(with open-ended groups extended to 120 years). This approach allows the population to then be
    aggregated to any requested set of age groups.

### Background mortality

Age-specific death rates are formed from UN deaths and population in each modelled age group. The open-ended oldest group is adjusted, then non-TB deaths are applied as replacement births into the uninfected youngest group.

UN death counts are recorded in thousands and are aggregated
to the model age groups with lower bounds 0, 3, 5, 10, 15, 18, 40, 65.
The last group is open-ended up to 120.

Age-specific background mortality is calculated from
the number of deaths divided by the population
in each model age group, reported by the UN.

The death rate in the oldest age group is multiplied by
2. In reality the hazard of death
rises with age, so the population in this open-ended group is
concentrated at its younger end, with only a thin tail at the
oldest ages. The rate taken from the data is the average
hazard weighted by that distribution.

The model applies a single constant hazard to the whole group,
which implies exponential attrition and a heavier old-age tail.
Without inflation, too many people remain in this group relative
to the reported age distribution.

Background (non-TB-related) mortality is applied as
an age-specific per capita rate,
interpolated over calendar time from the
death rates provided.

Each death is immediately replaced by a birth into the
_Mtb_-naive youngest age group. This keeps background
mortality from affecting the population size,
while returning newborns without prior infection.

### Population size

Replacement of deaths keeps background mortality from changing the total population. Extra entries, which may be negative, then match the UN totals. The run starts with the whole population uninfected.

Entry rates are calculated as the year-to-year increments
in total population, after inserting the model's
starting population at the start of the simulation.

Additional births enter the _Mtb_-naive youngest age group.
The supplied entry rates are applied as a step function in
calendar time.

Together with replacement of background deaths, this
produces a population that tracks the external totals while
remaining fully naive at birth.
Note that this entry rate may reach negative values,
but these negative entries are then more than compensated for by
the death replacements as births.

The simulation begins with the entire population in the
_Mtb_-naive compartment, distributed across the age groups
with lower bounds 0, 3, 5, 10, 15, 18, 40, 65 according to the supplied
starting age distribution.

## Natural history of tuberculosis

People occupy a small set of TB-related states, further split by age and, for active disease, by infectiousness and symptoms. Infection is seeded historically, then maintained by transmission.

All people within the simulation are assigned to one of the
following TB-related states: mtb_naive, incipient, contained, cleared, active, treatment, recovered.
These are stratified by age with lower bounds: 0, 3, 5, 10, 15, 18, 40, 65
years. Active TB is further stratified by infectiousness
(low, high) and by clinical status (subclinical or
clinical).

The model is solved at steps of 0.5 years.

Infection is seeded from the _Mtb_-naive compartment into
incipient infection with a triangular pulse. The pulse peaks
at the "seeding peak year" at a rate of "seeding peak rate",
with width "seeding duration".

### Infection

Infection moves susceptible people into incipient infection. The force of infection is age-specific and uses the mixing matrix described below.

Infection moves people from each of the susceptible states
mtb_naive, contained, cleared, recovered into incipient infection.

The force of infection is scaled by the
"raw transmission rate" and by a relative susceptibility
that depends on the source state: "relative susceptibility of the never-infected"
for the never-infected, "relative susceptibility of contained infection" for
contained infection, and "relative susceptibility of cleared or recovered infection" for both
cleared and recovered infection.

A time-varying mixing matrix is built from the
"background mixing", "assortative mixing spread" and "parent-child mixing strength"
parameters.

The force of infection is age-specific. Age groups whose
lower bound is below the young-age cutoff do not contribute
to transmission, and have susceptibility reduced by the
"relative susceptibility of children".

Each infectious person is weighted by the
"relative infectiousness of low-infectious TB" if in the low infectiousness
stratum, and by the "relative infectiousness of subclinical TB" if
subclinical. The resulting age-specific infectious pressure
is applied through the mixing matrix.

### Latency and progression

From incipient infection, people may contain infection or progress to active disease. Both rates vary by age.

Containment and progression rates are grouped into three
latency bands: under 5 years, 5 to under 15 years, and
15 years and over.

From incipient infection, people may contain infection or
progress to active disease. Both rates vary by the latency
age bands, using the "containment rate under 5 years",
"containment rate ages 5 to 15" and "containment rate ages 15 and over"
for containment, and the "progression rate under 5 years",
"progression rate ages 5 to 15" and "progression rate ages 15 and over"
for progression.

Progression is to subclinical disease. A fraction given by
the "proportion of progressions that are high-infectious" enter the high
infectiousness stratum, and the remainder enter the low
infectiousness stratum.

### Active disease

After infection is contained, people may clear infection
or undergo endogenous reactivation (breakdown), at the
"clearance rate" and "breakdown rate" respectively.

Among people with active TB, infectiousness may increase or
decrease at the "rate of infectiousness increase" and
"rate of infectiousness decrease". Symptoms may develop or
resolve at the "rate of clinical progression" and
"rate of clinical regression".

Subclinical disease may self-resolve at the
"self-recovery rate". Untreated clinical TB causes death
at the "TB mortality rate for low-infectious disease" or
"TB mortality rate for high-infectious disease", according to infectiousness.
These deaths are replaced by _Mtb_-naive births into the
youngest age group.

### Detection and treatment

Routine detection applies only to clinical disease. Treatment outcomes are derived from the success rate and the share of unsuccessful outcomes that are deaths, after allowing for background mortality during a course of treatment. Active case finding is a later, optional process and includes subclinical disease.

Routine detection moves people with clinical active TB into
treatment. Subclinical disease is not detected by this
process.

The rate of detection remains zero until 1957
and then follows a cosine-smoothed
scale-up through 1986 and 2010 to the "current detection rate"
in 2020. The 2010 rate is the current rate multiplied by the
"relative detection rate in 2010 compared to current", and the 1986 rate is that 2010 rate
multiplied by the "relative detection rate in 1986 compared to 2010".

The probability of background death during a course of
treatment is $1 - \exp(-\delta \mu)$, where $\delta$ is the
"treatment duration" and $\mu$ is the age-specific background
mortality rate.

The remaining outcomes are split using the treatment success
rate and the proportion of unsuccessful outcomes that are
deaths. Background deaths already counted are subtracted from
that death target, so that only the additional deaths
during treatment in excess of background mortality
are attributed to the TB-related mortality transition.
Whatever is left of the unsuccessful fraction
after these deaths is considered as relapse.
Success is calculated as the complement of
treatment-related death and relapse.

People on treatment leave to one of three outcomes, with
rates obtained from the treatment success rate, the
proportion of unsuccessful outcomes that are deaths, and
background mortality, all interpolated over calendar time.
The "treatment duration" sets the time scale of these rates.

Success returns people to the recovered compartment.
Relapse returns them to subclinical, low-infectious active TB.
Each death during treatment is replaced by an _Mtb_-naive birth
into the youngest age group.

Active case finding screens people with active TB and transitions
detected cases into treatment. Unlike routine detection, this
includes subclinical disease.

The peak rate is given by $-\ln(1 - c) \times s$, where $c$ is
"active case finding coverage" and $s$ is "active case finding sensitivity".
This converts annual coverage into a hazard over time,
and then scales this rate by diagnostic sensitivity.

The rate is zero until the "active case finding start year", rises over
the course of "active case finding scale-up time" years
to its peak rate as defined above,
remains at the peak for the "active case finding duration",
and then returns to zero.

## Population mixing

### Age weights for mixing

Within each model age group with lower bounds 0, 3, 5, 10, 15, 18, 40, 65,
the population at each single year of age is expressed as a
share of that group's total. The last group runs
to 120.

### Fertility

UN age-specific fertility rates are normalised so that they
sum to one across maternal ages in each year.
This provides the distribution of maternal ages at birth.

Ages without fertility data are filled with zeroes, covering
single years of age from 0 to 120.

### Mixing kernel

The single-age mixing kernel is the sum of three components
and does not depend on population size. It covers single years
of age from 0 to 120.

Background mixing is a constant "background mixing" added to
every age pair.

Assortative mixing decays exponentially with the difference
in age, as $(1/a)\exp(-|i-j|/a)$, where $a$ is the
"assortative mixing spread".

Parent-child mixing is the "parent-child mixing strength" multiplied by
fertility at the younger person's year of birth, indexed by
the age gap (the implied age of the parent at that birth).

### Within-group age weights

Each model age group with lower bounds 0, 3, 5, 10, 15, 18, 40, 65 is
represented as a distribution over single years of age,
using the supplied within-group weights, with the last
group running to 120.

### Aggregation to age groups

The group-level kernel is obtained by projecting the
single-age kernel through these within-group age
distributions. Each entry is the expected mixing intensity
between a random person from one age group and a random
person from another.

### Group mixing

Within-group age weights at the current year are used to
aggregate the single-age kernel to the modelled age groups.
The resulting matrix is a per pair of individuals intensity and
so does not yet incorporate population size.

### Population-scaled contacts

Each column of the group-level kernel is multiplied by the
population of that (infecting) age group, converting per pair of individuals
intensities into population-scaled contact rates.

### Mixing matrix normalisation

The population-scaled contact matrix is divided by its
spectral radius, such that the dominant eigenvalue is one.
This allows the intensity of transmission to be controlled through
other parameters, such that the mixing matrix construction controls
only the relative intensity of transmission between age groups.

## Programmatic outcomes

### Treatment success

We calculated treatment outcome rates directly from
the raw counts of outcomes provided by WHO.
Treatment success is the number cured or completing treatment,
pooled across new, retreatment and MDR cohorts, divided by
the size of those cohorts. Times are offset by
0.5 of a year to sit at mid-year.

### Deaths among unsuccessful treatment

The proportion of unsuccessful outcomes resulting in death
is calculated as deaths divided by deaths plus failure, default and
loss to follow-up, pooled across the same cohorts as for
the treatment success calculations. Times are offset by
0.5 of a year to sit at mid-year.

### WHO TB mortality

WHO burden estimates for the requested country are offset
by 0.5 of a year to sit at mid-year.

WHO estimates of TB deaths with and without HIV are summed
to a single mortality series.

## Outputs

### Incidence

Incidence is the progression flow from incipient infection
to active disease, summed within each modelled age group.

### Prevalence

Prevalence is calculated as the population in the compartments:
active, treatment. These are summed within each modelled age group.

### Pulmonary prevalence

The numerator comprises all active disease in the high infectiousness
stratum, a fraction of the low infectiousness stratum given by
"proportion of low-infectious TB that is bacteriologically positive", and everyone currently receiving
treatment. Clinical status does not enter this calculation.
Unlike the calibration target, all modelled age groups are
included.

### Clinical prevalence

Clinical prevalence is the population in the clinical
stratum of active TB (both high- and low-infectiousness),
summed within each modelled age group.

### Treatment prevalence

This is the population in the treatment compartment, summed
within each modelled age group.

### Recovered

This is the population in the recovered compartment, summed
within each modelled age group.

### Ever-infected

Latent (ever-infected) prevalence comprises everyone not in the
_Mtb_-naive compartment, that is: incipient, contained, cleared, active, treatment, recovered.
These are summed within each modelled age group.

### Notifications

Notifications are routine detection plus active case finding,
summed within each modelled age group.

### TB deaths

Deaths in the community and during treatment are summed
within each modelled age group.

### Mapping to output age groups

Each modelled age group is split across output age groups
according to the share of its population that overlaps each
output group, using single-year population counts.

Age-stratified outputs are reallocated from modelled age
groups to requested output age groups using the population
overlap fractions.

Age-stratified outputs are regrouped to the requested age
bands. Outputs without age structure are left unchanged
aside from aligning their times to the population data.

## Calibration

The log-likelihood is the sum of six contributions, taken as
independent: the prevalence of _Mtb_ infection, case notifications, TB
deaths, adult bacteriologically-confirmed prevalence, the decline in
prevalence between the two prevalence survey rounds,
and the proportion of prevalent disease that is highly infectious.

Two error models are applied throughout. Counts and ratios are compared
on the log scale, as
$\log \hat{y} \sim \mathcal{N}(\log y, \sigma_{c})$ with $\sigma_{c}$ of
0.1, so that the discrepancy scales with the magnitude of
the target. Proportions are compared on the log-odds scale, as
$\mathrm{logit}(\hat{p}) \sim \mathcal{N}(\mathrm{logit}(p), \sigma_{p})$
with $\sigma_{p}$ of 0.2, which respects their bounds at
zero and one. In both cases the transformed target provides the mean of
the distribution and the transformed modelled value is evaluated against
it, which is equivalent to the reverse for these symmetric
distributions.

Where a target spans multiple years, the log-density is averaged over
those years, so that each of the six contributions carries comparable
weight irrespective of how many observations it contains.

Parameter sets for which the solver does not reach a successful solution
are assigned a large negative log-likelihood, so that they are rejected
rather than contributing invalid model output to the likelihood.

### Prevalence of infection

The proportion of the population ever infected with _Mtb_ was compared
against the estimate from the tuberculin survey reported by Marks et al.
(Bulletin of the World Health Organization).

The modelled equivalent is everyone not previously infected with
_Mtb_, which is represented by all modelled compartments other than
_Mtb_ naive. That is, the incipient, contained, cleared, active, treatment, recovered states,
divided by the total population at the time of the survey.
All modelled age groups contributed to both the numerator and the denominator.

Being a proportion, this quantity was compared on the log-odds scale with
a standard deviation of 0.2.

### Notifications

Modelled case detections were compared against the notifications
obtained from the Vietnam National Tuberculosis Program. These are
reported by calendar year, and so are offset by
0.5 of a year to sit at mid-year in model time
(because we consider whole numbers of years in modelled time
to represent the starts and ends of years).

As counts, notifications are compared on the log scale with a
standard deviation of 0.1, which relates the difference
to the size of the target, rather than being absolute.
The log-density is averaged rather than summed over the years of data, so
that this multi-year series contributes comparable weight to the likelihood
as the single-point targets.

### Deaths

Modelled TB deaths are compared against the WHO estimates of TB
mortality for VNM. Deaths occurring in the community and during
treatment are summed before comparison, because the estimates do not
distinguish between them.

As for notifications, these counts are compared on the log scale with a
standard deviation of 0.1, and averaged over the years for
which estimates are available.

### Definition of prevalent disease

Prevalence is calculated to approximate the quantity ascertained by a
bacteriologically confirmed prevalence survey, and so is restricted to
adults, taken here as those aged 15 years and over.

Three groups contribute to the numerator: all those with active disease
in the high infectiousness stratum, a fraction of those in the low
infectiousness stratum given by the "proportion of low-infectious TB that is bacteriologically positive", and
everyone currently receiving treatment. Clinical status does not
enter this calculation, such that subclinical disease contributes
on the same basis as clinical disease.

The denominator is the total adult population at the same time point.

### Prevalence of pulmonary disease

Modelled adult prevalence of bacteriologically confirmed pulmonary TB was
compared against the second Vietnamese national prevalence survey
(PLOS One). The target is published per 100,000 population and converted
to a proportion of the adult population.

Being a proportion, this quantity was compared on the log-odds scale with
a standard deviation of 0.2.

### Decline in prevalence

The two survey rounds reported by Nguyen et al. (Emerging Infectious
Diseases) are used to target the decline in prevalence rather than absolute values.
Only the ratio of the later to the earlier estimate is taken,
so that the target constrains the trend in prevalence while remaining
insensitive to any discrepancy between the quantity these surveys
assess and our definition of prevalence.

The modelled ratio applies the same adult prevalence definition at both
time points. The ratio is strictly positive, so it is compared on the
log scale with a standard deviation of 0.1.

### Infectiousness of prevalent disease

The proportion of prevalent adult TB that is highly infectious was
compared against the equivalent proportion from the second Vietnamese
national prevalence survey.

The numerator is the high infectiousness stratum of the active
compartment and the denominator is total adult prevalence, as defined
above. This target therefore constrains how prevalent disease is
distributed across the infectiousness strata, without further
constraining the overall size of the prevalent pool.

As a proportion, this quantity is compared on the log-odds scale with
a standard deviation of 0.2.

### UN population

Population counts are taken from the UN World Population
Prospects, by calendar year and age group, for country: VNM.

UN age-group counts are recorded in thousands and are
distributed uniformly across the single years of age
contained by each group before further processing
(with open-ended groups extended to 120 years).

### Model age groups

Individual integer years of age are assigned to the model age groups with
lower bounds 0, 3, 5, 10, 15, 18, 40, 65. The last group is open-ended up
to 120.

### UN mortality

UN death counts are recorded in thousands and are aggregated
to the model age groups with lower bounds 0, 3, 5, 10, 15, 18, 40, 65.
The last group is open-ended up to 120.

### Ageing

The population is stratified into age groups with lower bounds of:
0, 3, 5, 10, 15, 18, 40, 65 years. People move from each group to the next at a
constant rate equal to the reciprocal of the with of the group
they are exiting in years, such that the mean time spent in
each age group matches its width. The oldest group has
no ageing outflow. Exit from this group occurs only through death.

### Oldest age group mortality

The death rate in the oldest age group is multiplied by
2. In reality the hazard of death
rises with age, so the population in this open-ended group is
concentrated at its younger end, with only a thin tail at the
oldest ages. The rate taken from the data is the average
hazard weighted by that distribution.

The model applies a single constant hazard to the whole group,
which implies exponential attrition and a heavier old-age tail.
Without inflation, too many people remain in this group relative
to the reported age distribution.

### Background mortality

Background (non-TB-related) mortality is applied as
an age-specific per capita rate,
interpolated over calendar time from the
death rates provided.

Each death is immediately replaced by a birth into the
_Mtb_-naive youngest age group. This keeps background
mortality from affecting the population size,
while returning newborns without prior infection.

### Construction of entry rates

Entry rates are calculated as the year-to-year increments
in total population, after inserting the model's
starting population at the start of the simulation.

### Population growth

Additional births enter the _Mtb_-naive youngest age group.
The supplied entry rates are applied as a step function in
calendar time.

Together with replacement of background deaths, this
produces a population that tracks the external totals while
remaining fully naive at birth.
Note that this entry rate may reach negative values,
but these negative entries are then more than compensated for by
the death replacements as births.

## Epidemiological model construction

### Compartments and stratifications

All people within the simulation are assigned to one of the
following TB-related states: mtb_naive, incipient, contained, cleared, active, treatment, recovered.
These are stratified by age with lower bounds: 0, 3, 5, 10, 15, 18, 40, 65
years. Active TB is further stratified by infectiousness
(low, high) and by clinical status (subclinical or
clinical).

The model is solved at steps of 0.5 years.

### Initial population

The simulation begins with the entire population in the
_Mtb_-naive compartment, distributed across the age groups
with lower bounds 0, 3, 5, 10, 15, 18, 40, 65 according to the supplied
starting age distribution.

### Seeding

Infection is seeded from the _Mtb_-naive compartment into
incipient infection with a triangular pulse. The pulse peaks
at the "seeding peak year" at a rate of "seeding peak rate",
with width "seeding duration".

### Force of infection

The force of infection is age-specific. Age groups whose
lower bound is below the young-age cutoff do not contribute
to transmission, and have susceptibility reduced by the
"relative susceptibility of children".

Each infectious person is weighted by the
"relative infectiousness of low-infectious TB" if in the low infectiousness
stratum, and by the "relative infectiousness of subclinical TB" if
subclinical. The resulting age-specific infectious pressure
is applied through the mixing matrix.

### Infection

Infection moves people from each of the susceptible states
mtb_naive, contained, cleared, recovered into incipient infection.

The force of infection is scaled by the
"raw transmission rate" and by a relative susceptibility
that depends on the source state: "relative susceptibility of the never-infected"
for the never-infected, "relative susceptibility of contained infection" for
contained infection, and "relative susceptibility of cleared or recovered infection" for both
cleared and recovered infection.

A time-varying mixing matrix is built from the
"background mixing", "assortative mixing spread" and "parent-child mixing strength"
parameters.

### Latency age bands

Containment and progression rates are grouped into three
latency bands: under 5 years, 5 to under 15 years, and
15 years and over.

### Latency

From incipient infection, people may contain infection or
progress to active disease. Both rates vary by the latency
age bands, using the "containment rate under 5 years",
"containment rate ages 5 to 15" and "containment rate ages 15 and over"
for containment, and the "progression rate under 5 years",
"progression rate ages 5 to 15" and "progression rate ages 15 and over"
for progression.

Progression is to subclinical disease. A fraction given by
the "proportion of progressions that are high-infectious" enter the high
infectiousness stratum, and the remainder enter the low
infectiousness stratum.

### Natural history

After infection is contained, people may clear infection
or undergo endogenous reactivation (breakdown), at the
"clearance rate" and "breakdown rate" respectively.

Among people with active TB, infectiousness may increase or
decrease at the "rate of infectiousness increase" and
"rate of infectiousness decrease". Symptoms may develop or
resolve at the "rate of clinical progression" and
"rate of clinical regression".

Subclinical disease may self-resolve at the
"self-recovery rate". Untreated clinical TB causes death
at the "TB mortality rate for low-infectious disease" or
"TB mortality rate for high-infectious disease", according to infectiousness.
These deaths are replaced by _Mtb_-naive births into the
youngest age group.

### Detection

Routine detection moves people with clinical active TB into
treatment. Subclinical disease is not detected by this
process.

The rate of detection remains zero until 1957
and then follows a cosine-smoothed
scale-up through 1986 and 2010 to the "current detection rate"
in 2020. The 2010 rate is the current rate multiplied by the
"relative detection rate in 2010 compared to current", and the 1986 rate is that 2010 rate
multiplied by the "relative detection rate in 1986 compared to 2010".

### Treatment outcome proportions

The probability of background death during a course of
treatment is $1 - \exp(-\delta \mu)$, where $\delta$ is the
"treatment duration" and $\mu$ is the age-specific background
mortality rate.

The remaining outcomes are split using the treatment success
rate and the proportion of unsuccessful outcomes that are
deaths. Background deaths already counted are subtracted from
that death target, so that only the additional deaths
during treatment in excess of background mortality
are attributed to the TB-related mortality transition.
Whatever is left of the unsuccessful fraction
after these deaths is considered as relapse.
Success is calculated as the complement of
treatment-related death and relapse.

### Treatment outcome rates

Each treatment outcome proportion is converted to a
competing hazard by dividing by the treatment duration.

### Treatment

People on treatment leave to one of three outcomes, with
rates obtained from the treatment success rate, the
proportion of unsuccessful outcomes that are deaths, and
background mortality, all interpolated over calendar time.
The "treatment duration" sets the time scale of these rates.

Success returns people to the recovered compartment.
Relapse returns them to subclinical, low-infectious active TB.
Each death during treatment is replaced by an _Mtb_-naive birth
into the youngest age group.

### Active case finding

Active case finding screens people with active TB and transitions
detected cases into treatment. Unlike routine detection, this
includes subclinical disease.

The peak rate is given by $-\ln(1 - c) \times s$, where $c$ is
"active case finding coverage" and $s$ is "active case finding sensitivity".
This converts annual coverage into a hazard over time,
and then scales this rate by diagnostic sensitivity.

The rate is zero until the "active case finding start year", rises over
the course of "active case finding scale-up time" years
to its peak rate as defined above,
remains at the peak for the "active case finding duration",
and then returns to zero.

## Population mixing

### Age weights for mixing

Within each model age group with lower bounds 0, 3, 5, 10, 15, 18, 40, 65,
the population at each single year of age is expressed as a
share of that group's total. The last group runs
to 120.

### Fertility

UN age-specific fertility rates are normalised so that they
sum to one across maternal ages in each year.
This provides the distribution of maternal ages at birth.

Ages without fertility data are filled with zeroes, covering
single years of age from 0 to 120.

### Mixing kernel

The single-age mixing kernel is the sum of three components
and does not depend on population size. It covers single years
of age from 0 to 120.

Background mixing is a constant "background mixing" added to
every age pair.

Assortative mixing decays exponentially with the difference
in age, as $(1/a)\exp(-|i-j|/a)$, where $a$ is the
"assortative mixing spread".

Parent-child mixing is the "parent-child mixing strength" multiplied by
fertility at the younger person's year of birth, indexed by
the age gap (the implied age of the parent at that birth).

### Within-group age weights

Each model age group with lower bounds 0, 3, 5, 10, 15, 18, 40, 65 is
represented as a distribution over single years of age,
using the supplied within-group weights, with the last
group running to 120.

### Aggregation to age groups

The group-level kernel is obtained by projecting the
single-age kernel through these within-group age
distributions. Each entry is the expected mixing intensity
between a random person from one age group and a random
person from another.

### Group mixing

Within-group age weights at the current year are used to
aggregate the single-age kernel to the modelled age groups.
The resulting matrix is a per pair of individuals intensity and
so does not yet incorporate population size.

### Population-scaled contacts

Each column of the group-level kernel is multiplied by the
population of that (infecting) age group, converting per pair of individuals
intensities into population-scaled contact rates.

### Mixing matrix normalisation

The population-scaled contact matrix is divided by its
spectral radius, such that the dominant eigenvalue is one.
This allows the intensity of transmission to be controlled through
other parameters, such that the mixing matrix construction controls
only the relative intensity of transmission between age groups.

## Programmatic outcomes

### Treatment success

We calculated treatment outcome rates directly from
the raw counts of outcomes provided by WHO.
Treatment success is the number cured or completing treatment,
pooled across new, retreatment and MDR cohorts, divided by
the size of those cohorts. Times are offset by
0.5 of a year to sit at mid-year.

### Deaths among unsuccessful treatment

The proportion of unsuccessful outcomes resulting in death
is calculated as deaths divided by deaths plus failure, default and
loss to follow-up, pooled across the same cohorts as for
the treatment success calculations. Times are offset by
0.5 of a year to sit at mid-year.

### WHO TB mortality

WHO burden estimates for the requested country are offset
by 0.5 of a year to sit at mid-year.

WHO estimates of TB deaths with and without HIV are summed
to a single mortality series.

## Outputs

### Incidence

Incidence is the progression flow from incipient infection
to active disease, summed within each modelled age group.

### Prevalence

Prevalence is calculated as the population in the compartments:
active, treatment. These are summed within each modelled age group.

### Pulmonary prevalence

The numerator comprises all active disease in the high infectiousness
stratum, a fraction of the low infectiousness stratum given by
"proportion of low-infectious TB that is bacteriologically positive", and everyone currently receiving
treatment. Clinical status does not enter this calculation.
Unlike the calibration target, all modelled age groups are
included.

### Clinical prevalence

Clinical prevalence is the population in the clinical
stratum of active TB (both high- and low-infectiousness),
summed within each modelled age group.

### Treatment prevalence

This is the population in the treatment compartment, summed
within each modelled age group.

### Recovered

This is the population in the recovered compartment, summed
within each modelled age group.

### Ever-infected

Latent (ever-infected) prevalence comprises everyone not in the
_Mtb_-naive compartment, that is: incipient, contained, cleared, active, treatment, recovered.
These are summed within each modelled age group.

### Notifications

Notifications are routine detection plus active case finding,
summed within each modelled age group.

### TB deaths

Deaths in the community and during treatment are summed
within each modelled age group.

### Mapping to output age groups

Each modelled age group is split across output age groups
according to the share of its population that overlaps each
output group, using single-year population counts.

Age-stratified outputs are reallocated from modelled age
groups to requested output age groups using the population
overlap fractions.

Age-stratified outputs are regrouped to the requested age
bands. Outputs without age structure are left unchanged
aside from aligning their times to the population data.

## Calibration

The log-likelihood is the sum of six contributions, taken as
independent: the prevalence of _Mtb_ infection, case notifications, TB
deaths, adult bacteriologically-confirmed prevalence, the decline in
prevalence between the two prevalence survey rounds,
and the proportion of prevalent disease that is highly infectious.

Two error models are applied throughout. Counts and ratios are compared
on the log scale, as
$\log \hat{y} \sim \mathcal{N}(\log y, \sigma_{c})$ with $\sigma_{c}$ of
0.1, so that the discrepancy scales with the magnitude of
the target. Proportions are compared on the log-odds scale, as
$\mathrm{logit}(\hat{p}) \sim \mathcal{N}(\mathrm{logit}(p), \sigma_{p})$
with $\sigma_{p}$ of 0.2, which respects their bounds at
zero and one. In both cases the transformed target provides the mean of
the distribution and the transformed modelled value is evaluated against
it, which is equivalent to the reverse for these symmetric
distributions.

Where a target spans multiple years, the log-density is averaged over
those years, so that each of the six contributions carries comparable
weight irrespective of how many observations it contains.

Parameter sets for which the solver does not reach a successful solution
are assigned a large negative log-likelihood, so that they are rejected
rather than contributing invalid model output to the likelihood.

### Prevalence of infection

The proportion of the population ever infected with _Mtb_ was compared
against the estimate from the tuberculin survey reported by Marks et al.
(Bulletin of the World Health Organization).

The modelled equivalent is everyone not previously infected with
_Mtb_, which is represented by all modelled compartments other than
_Mtb_ naive. That is, the incipient, contained, cleared, active, treatment, recovered states,
divided by the total population at the time of the survey.
All modelled age groups contributed to both the numerator and the denominator.

Being a proportion, this quantity was compared on the log-odds scale with
a standard deviation of 0.2.

### Notifications

Modelled case detections were compared against the notifications
obtained from the Vietnam National Tuberculosis Program. These are
reported by calendar year, and so are offset by
0.5 of a year to sit at mid-year in model time
(because we consider whole numbers of years in modelled time
to represent the starts and ends of years).

As counts, notifications are compared on the log scale with a
standard deviation of 0.1, which relates the difference
to the size of the target, rather than being absolute.
The log-density is averaged rather than summed over the years of data, so
that this multi-year series contributes comparable weight to the likelihood
as the single-point targets.

### Deaths

Modelled TB deaths are compared against the WHO estimates of TB
mortality for VNM. Deaths occurring in the community and during
treatment are summed before comparison, because the estimates do not
distinguish between them.

As for notifications, these counts are compared on the log scale with a
standard deviation of 0.1, and averaged over the years for
which estimates are available.

### Definition of prevalent disease

Prevalence is calculated to approximate the quantity ascertained by a
bacteriologically confirmed prevalence survey, and so is restricted to
adults, taken here as those aged 15 years and over.

Three groups contribute to the numerator: all those with active disease
in the high infectiousness stratum, a fraction of those in the low
infectiousness stratum given by the "proportion of low-infectious TB that is bacteriologically positive", and
everyone currently receiving treatment. Clinical status does not
enter this calculation, such that subclinical disease contributes
on the same basis as clinical disease.

The denominator is the total adult population at the same time point.

### Prevalence of pulmonary disease

Modelled adult prevalence of bacteriologically confirmed pulmonary TB was
compared against the second Vietnamese national prevalence survey
(PLOS One). The target is published per 100,000 population and converted
to a proportion of the adult population.

Being a proportion, this quantity was compared on the log-odds scale with
a standard deviation of 0.2.

### Decline in prevalence

The two survey rounds reported by Nguyen et al. (Emerging Infectious
Diseases) are used to target the decline in prevalence rather than absolute values.
Only the ratio of the later to the earlier estimate is taken,
so that the target constrains the trend in prevalence while remaining
insensitive to any discrepancy between the quantity these surveys
assess and our definition of prevalence.

The modelled ratio applies the same adult prevalence definition at both
time points. The ratio is strictly positive, so it is compared on the
log scale with a standard deviation of 0.1.

### Infectiousness of prevalent disease

The proportion of prevalent adult TB that is highly infectious was
compared against the equivalent proportion from the second Vietnamese
national prevalence survey.

The numerator is the high infectiousness stratum of the active
compartment and the denominator is total adult prevalence, as defined
above. This target therefore constrains how prevalent disease is
distributed across the infectiousness strata, without further
constraining the overall size of the prevalent pool.

As a proportion, this quantity is compared on the log-odds scale with
a standard deviation of 0.2.

## Fixed parameters

In [3]:
fixed_params = {k: v for k, v in BASE_PARAMS.items() if k not in PARAM_BOUNDS}
build_fixed_params_table(fixed_params)

                                                       value
Parameter
relative susceptibility of the never-infected              1
relative infectiousness of subclinical TB                0.5
relative infectiousness of low-infectious TB             0.4
progression rate under 5 years                           2.4
progression rate ages 5 to 15                              2
progression rate ages 15 and over                        0.1
proportion of progressions that are high-infect...       0.5
containment rate under 5 years                           4.4
containment rate ages 5 to 15                            4.4
containment rate ages 15 and over                          2
rate of clinical regression                                1
rate of infectiousness decrease                            1
TB mortality rate for high-infectious disease          0.389
TB mortality rate for low-infectious disease           0.025
self-recovery rate                                       0.4
treatment duration                                       0.5
seeding peak year                                       1830
seeding duration                                          10
seeding peak rate                                       0.01
active case finding coverage                               0
active case finding sensitivity                            0
active case finding start year                          2027
active case finding duration                               5
active case finding scale-up time                          1
proportion of low-infectious TB that is bacteri...  0.666667

## Prior ranges

Pass the dict of prior bounds to show.

In [4]:
build_prior_ranges_table(PARAM_BOUNDS)

                                                    lower upper
Parameter
raw transmission rate                                  12    20
background mixing                                   0.002  0.04
assortative mixing spread                               5    15
parent-child mixing strength                            1   2.5
relative susceptibility of contained infection        0.2   0.6
relative susceptibility of cleared or recovered...    0.5     1
relative susceptibility of children                   0.5     1
breakdown rate                                       0.01     1
clearance rate                                       0.01   0.1
rate of clinical progression                         0.25     2
rate of infectiousness increase                      0.25     2
current detection rate                                0.5   1.5
relative detection rate in 2010 compared to cur...    0.5     1
relative detection rate in 1986 compared to 2010     0.25  0.75