---
title: "Methods"
format: 
  pdf:
    toc: true
execute:
  echo: false
  warning: false
jupyter: python3
---

In [1]:
from IPython.display import Markdown, display
import pandas as pd

from tb_macro.document import get_func_notes, build_fixed_params_table, build_prior_ranges_table
from tb_macro.acf import add_acf
from tb_macro.health_system import (
    add_detection,
    add_treatment_flows,
    compute_outcome_props,
    get_outcome_rates,
)
from tb_macro.inputs import (
    add_groups_to_single_pop,
    build_age_weight_lookup,
    calc_death_in_unsucc_outcomes,
    calc_tsr_from_outcomes,
    get_norm_conmat,
    get_country_indicators,
    get_country_pop,
    get_fertility_data,
    get_single_age_pop_from_ungroups,
    get_un_mortality,
    load_demography,
    load_fertility,
    load_who_outcomes,
)
from tb_macro.mixing import (
    aggregate_full_matrix_to_groups,
    build_c_matrix,
    build_s_matrix_single_age,
    get_norm_c_matrix,
    canberra_distance,
)
from tb_macro.demography import (
    add_ageing_flows,
    add_entry_births,
    add_replacement_deaths,
    inflate_oldest_death_rates,
    prepare_pop_data_for_entries,
)
from tb_macro.epi import (
    add_infection_flows,
    add_latency_flows,
    add_natural_history,
    add_seeding,
    get_base_model,
    get_latency_age_adj,
    infect_process,
    initialise_pops,
)
from tb_macro.calibration import (
    make_log_likelihood,
    get_latent_log_likelihood,
    get_notification_log_likelihood,
    get_death_log_likelihood,
    get_adult_pulm_prev,
    get_pulm_prev_log_likelihood,
    get_prev_decline_log_likelihood,
    get_infprop_log_likelihood,
    get_mixing_log_likelihood,
)
from tb_macro.outputs import (
    build_age_mapping,
    get_age_deaths,
    get_age_inc,
    get_age_notifs,
    get_age_prev,
    get_age_pulm_prev,
    get_age_rx_prev,
    map_and_regroup_output,
    regroup_full_outputs,
)
from tb_macro.parameters import BASE_PARAMS, PARAM_BOUNDS

/Users/jamestrauer/dev/tb_macroeconomics/.pixi/envs/default/lib/python3.13/site-packages/arviz/__init__.py:50: FutureWarning:
ArviZ is undergoing a major refactor to improve flexibility and extensibility while maintaining a user-friendly interface.
Some upcoming changes may be backward incompatible.
For details and migration guidance, visit: https://python.arviz.org/en/latest/user_guide/migration_guide.html
  warn(

In [2]:
display(Markdown("""# Demographics
The modelled population is stratified by age. 
Our demographic model is designed to exactly match total population size estimates,
be mechanistically coherent and to support a realistic population distribution by age 
to emerge from the applied demographic processes.
"""))
display(Markdown("""## Age groups"""))
display(Markdown(get_func_notes(add_ageing_flows)))

display(Markdown("""## Population data"""))
display(Markdown(
    get_func_notes(get_country_pop) + " " +
    get_func_notes(get_single_age_pop_from_ungroups) +
    """ This approach allows the population to then be
    aggregated to any requested set of age groups.
    """
    )
)
display(Markdown("""## Background mortality"""))
display(Markdown("""Age-specific death rates are formed from 
deaths and populations reported by the UN in each modelled age group. Non-TB deaths are 
applied as replacement births into the youngest uninfected group.
""" + get_func_notes(get_un_mortality) + " " + 
get_func_notes(load_demography) + "\n\n" + get_func_notes(inflate_oldest_death_rates) +
"\n\n" + get_func_notes(add_replacement_deaths)
))
display(Markdown("""## Population size"""))
display(Markdown(get_func_notes(initialise_pops)))
display(Markdown("""As described above, 
the replacement of deaths keeps background mortality from affecting 
the total population size. 
Each model run starts with an entirely uninfected population
assigned to the _Mtb_-naive state.
""" + get_func_notes(prepare_pop_data_for_entries)
))
display(Markdown(get_func_notes(add_entry_births)))

display(Markdown("""# Natural history of tuberculosis"""))
display(Markdown(get_func_notes(get_base_model)))
display(Markdown("""## Seeding"""))
display(Markdown(get_func_notes(add_seeding)))
display(Markdown("""## Infection"""))
display(Markdown(get_func_notes(add_infection_flows) + " " + get_func_notes(infect_process)))
display(Markdown("""## Progression through infection and disease states"""))
display(Markdown(get_func_notes(get_latency_age_adj) + " " + get_func_notes(add_latency_flows) + " " + get_func_notes(add_natural_history)))

display(Markdown("# Population mixing"))
display(Markdown("## Mixing kernel"))
display(Markdown(get_func_notes(build_s_matrix_single_age) + " " + get_func_notes(get_fertility_data) + " " + get_func_notes(load_fertility)))
display(Markdown("## Aggregation"))
display(Markdown(get_func_notes(build_age_weight_lookup) + " " + get_func_notes(aggregate_full_matrix_to_groups) + " " + get_func_notes(build_c_matrix)))
display(Markdown("## Normalisation"))
display(Markdown(get_func_notes(get_norm_c_matrix)))

display(Markdown("""# Health system"""))
display(Markdown("## Detection"))
display(Markdown(get_func_notes(add_detection)))
display(Markdown("## Treatment"))
display(Markdown(get_func_notes(calc_tsr_from_outcomes) + " " + get_func_notes(calc_death_in_unsucc_outcomes) + " " + get_func_notes(compute_outcome_props)))
display(Markdown(get_func_notes(add_treatment_flows)))
display(Markdown(get_func_notes(get_outcome_rates)))

display(Markdown("# Active case finding"))
display(Markdown(get_func_notes(add_acf)))

display(Markdown("# Model outputs"))
output_defs = {
    "Incidence": get_func_notes(get_age_inc),
    "Prevalence": get_func_notes(get_age_prev),
    "Pulmonary prevalence": get_func_notes(get_age_pulm_prev),
    "Treatment prevalence": get_func_notes(get_age_rx_prev),
    "Notifications": get_func_notes(get_age_notifs),
    "TB deaths": get_func_notes(get_age_deaths),
}
output_defs = {"Definition": {k: " ".join(v.split()) for k, v in output_defs.items()}}
display(Markdown(pd.DataFrame(output_defs).rename_axis("Indicator").to_markdown() + "\n\n: {tbl-colwidths=\"[30,70]\"}"))
display(Markdown("## Mapping to output age groups"))
display(Markdown(get_func_notes(build_age_mapping) + " " + get_func_notes(map_and_regroup_output) + " " + get_func_notes(regroup_full_outputs)))

display(Markdown("# Calibration\n## Likelihood construction"))
display(Markdown(get_func_notes(make_log_likelihood)))
display(Markdown("## Target calculations"))
display(Markdown("### Prevalence of infection"))
display(Markdown(get_func_notes(get_latent_log_likelihood)))
display(Markdown("### Notifications"))
display(Markdown(get_func_notes(get_notification_log_likelihood)))
display(Markdown("### Deaths"))
display(Markdown(
    get_func_notes(load_who_outcomes) + " " +
    get_func_notes(get_country_indicators) + " " +
    get_func_notes(get_death_log_likelihood)
))
display(Markdown("### Pulmonary prevalence"))
display(Markdown(
    get_func_notes(get_adult_pulm_prev) + " " +
    get_func_notes(get_pulm_prev_log_likelihood) +
    "\n\n" + get_func_notes(get_prev_decline_log_likelihood) +
    "\n\n" + get_func_notes(get_infprop_log_likelihood)
))
display(Markdown("### Mixing matrix"))
display(Markdown(
    get_func_notes(get_mixing_log_likelihood) +
    "\n\n" + get_func_notes(canberra_distance)
))

# Demographics
The modelled population is stratified by age.
Our demographic model is designed to exactly match total population size estimates,
be mechanistically coherent and to support a realistic population distribution by age
to emerge from the applied demographic processes.

## Age groups

The population is stratified into age groups with lower bounds of:
0, 3, 5, 10, 15, 18, 40, 65 years. People move from each group to the next at a
constant rate equal to the reciprocal of the with of the group
they are exiting in years, such that the mean time spent in
each age group matches its width. The oldest group has
no ageing outflow; exit from this group occurs only through death.

## Population data

Population counts are taken from the UN World Population
Prospects, by calendar year and age group, for country: VNM. UN age-group counts are recorded in thousands and are
distributed uniformly across the single years of age
contained by each group before further processing
to modelled age brackets (with open-ended groups extended
to 120 years). This approach allows the population to then be
    aggregated to any requested set of age groups.

## Background mortality

Age-specific death rates are formed from
deaths and populations reported by the UN in each modelled age group. Non-TB deaths are
applied as replacement births into the youngest uninfected group.
UN death counts are recorded in thousands and are aggregated
to our modelled age groups (with lower bounds 0, 3, 5, 10, 15, 18, 40, 65).
For the purposes of mortality calculations, the last group is
considered to include persons aged up to 120 years. Age-specific background mortality is calculated from
the total number of reported deaths divided by the population
size of each model age group.

In reality the hazard of death rises with age,
so the population in this open-ended group is
concentrated at its younger end, with only a thin tail at the
oldest ages. The unadjusted rate taken from the data is
therefore the average hazard weighted by that distribution.
By contrast, our model applies a single constant hazard to the whole group,
which implies exponential attrition and a heavier old-age tail.
Without inflation, too many people remain in this group relative
to the reported age distribution.
To address these issues, the death rate in the oldest age group
was multiplied by 2.

Background (non-TB-related) mortality is applied as
age-specific per capita rates,
interpolated over calendar time from the
death rates calculated.
Each death is immediately replaced by a birth into the
_Mtb_-naive youngest age group. This keeps background
mortality from affecting the population size,
while returning newborns without prior infection.

## Population size

The simulation begins with the entire population assigned to the
_Mtb_-naive compartment, distributed across the modelled age groups
according to the requested starting age distribution.

As described above,
the replacement of deaths keeps background mortality from affecting
the total population size.
Each model run starts with an entirely uninfected population
assigned to the _Mtb_-naive state.
Entry rates (births in addition to the death replacements,
which may be negative) are calculated as the year-to-year increments
in total population, after additionally inserting the model's
starting population at the start of the simulation.

Births enter the youngest _Mtb_-naive age group.
The supplied entry rates are applied as a step function over calendar time.
Together with replacement of background deaths, this
produces a population that closely tracks
the totals targeted, while ensuring that the population remains
fully infection-naive at birth. Negative entries are more than compensated by
the death replacements as births.

# Natural history of tuberculosis

All people within the simulation are assigned to one of the
following TB-related states: mtb_naive, incipient, contained, cleared, active, treatment, recovered.
Active TB is further stratified by infectiousness
(low, high) and by clinical status (clin, subclin).

## Seeding

Infection is seeded by transitioning people from
the _Mtb_-naive compartment into incipient infection
with a triangular pulse. The pulse peaks at the
"seeding peak year" at a rate of "seeding peak rate",
with width "seeding duration".

## Infection

Infection moves people from each of the susceptible states
(mtb_naive, contained, cleared, recovered) into incipient infection.
The force of infection is scaled by the
"raw transmission rate" parameter and by
a relative susceptibility that depends on
the source state: "relative susceptibility of the never-infected"
for the never-infected, "relative susceptibility of contained infection" for
contained infection, and "relative susceptibility of cleared or recovered infection" for both
cleared and recovered infection.
Never-infected children have their susceptibility further
reduced by the "relative susceptibility of never-infected children" parameter.
This age-specific modifier is not applied to reinfection from
contained, cleared or recovered infection,
because previous infection or disease is assumed to
override any effect of BCG. A time-varying age-structured
mixing matrix is built from the "background mixing",
"assortative mixing spread" and "parent-child mixing strength" parameters. Age groups whose lower bound is below the young-age cutoff
of 15 do not contribute to transmission.
Each infectious person's contribution to the force of infection
is weighted by the "relative infectiousness of low-infectious TB" if in
the low infectiousness stratum, and by the
"relative infectiousness of subclinical TB" if subclinical.

## Progression through infection and disease states

Containment and progression rates are grouped into three
latency bands: under 5 years, 5 to under 15 years, and
15 years and over. From incipient infection, people may contain infection or
progress to active disease. Both rates vary according to
the latency age bands, using the "containment rate under 5 years",
"containment rate ages 5 to 15" and "containment rate ages 15 and over"
parameters for containment, and the "progression rate under 5 years",
"progression rate ages 5 to 15" and "progression rate ages 15 and over"
parameters for progression. All progression is to subclinical disease.
A fraction of new disesae episodes, given by
the "proportion of progressions that are high-infectious", enter
the high infectiousness stratum, with the remainder entering
the low infectiousness stratum. After infection is contained, people may clear infection
or undergo endogenous reactivation (breakdown), according to
the "clearance rate" and "breakdown rate" parameters,
respectively. Among people with active TB,
infectiousness may increase or decrease at
the "rate of infectiousness increase" and
"rate of infectiousness decrease", respectively.
Symptoms may develop or resolve at the
"rate of clinical progression" and
"rate of clinical regression".
Subclinical disease may self-resolve at the
"self-recovery rate". Untreated clinical TB causes death
at the "TB mortality rate for low-infectious disease" or
"TB mortality rate for high-infectious disease", according to infectiousness level.
As for background mortality, these deaths are also replaced
by _Mtb_-naive births into the youngest age group.

# Population mixing

## Mixing kernel

The single-age mixing kernel is the sum of three components and
is independent of population size. That is, it represents
the frequency of contact between two specific individuals
from each of the two nominated age groups come into contact.
It is calculated in single years of age from 0 to 120.
To populate this matrix, background mixing is first added as
a constant value to every age group pair, using the parameter "background mixing".
Assortative mixing between closer ages is then added as a function that
decays exponentially with increasing difference
in age between each pair of groups ($i$ and $j$), as
$(1/a)\exp(-|i-j|/a)$, where $a$ is the "assortative mixing spread" parameter.
Last, parent-child mixing is added by multiplying
the "parent-child mixing strength" parameter by fertility at
the younger person's year of birth, indexed by the age gap
(that is, the implied age of the parent at that birth).
As such, this mixing kernel changes over time throughout
the simulation according to fertility data inputs.
Further, the relative strength of each fo the three
contributions to mixing are adjusted at each calibration iteration. Age-specific fertility rates obtained from the UN were normalised
such that they sum to one over maternal ages for each modelled year.
This provides the evolving distribution of maternal ages at birth. Ages without fertility data are filled with zeroes,
to ensure coverage of all single years of age from 0 to 120.

## Aggregation

Within each modelled age group, the population of each single year of age
is expressed as a share of the group's total. The last group runs
to 120 for the purposes of this aggregation calculation. The group-level kernel is obtained by aggregating the
single-age kernel using these within-group age distributions.
Each cell value of the resulting matrix represents the mixing intensity
between an individual from one age group and one from the other. Each column of the group-level kernel is multiplied by the population of
that (i.e. the infecting) age group, converting the per pair of individuals
intensities into population-scaled contact rates.
The resulting matrix contains values represents the rate at which
a person from the age group represented by each row of the matrix
comes into contact with _any_ person from the age group represented by
the column.

## Normalisation

The population-scaled contact matrix is divided by its
spectral radius, such that the dominant eigenvalue is one.
This allows the intensity of transmission to be controlled through
other parameters, such that the mixing matrix construction controls
the relative intensity of transmission between age groups.

# Health system

## Detection

Passive case detection moves people with clinical active TB onto
treatment. Only clinical disease is detected by this process,
with subclinical disease not affected.
The rate of detection remains zero until 1957 and then
follows a cosine-smoothed scale-up through 1986 and 2007
to the "current detection rate" in 2020. The 2007 rate is
the current rate multiplied by the "relative detection rate in 2007 compared to current" parameter,
and the 1986 rate is that 2007 rate multiplied by the "relative detection rate in 1986 compared to 2007".
To account for the effects of the COVID-19 pandemic,
detection falls in 2021 to the current detection rate multiplied by the
"COVID-19-related detection reduction" parameter, before returning to the current rate in 2022.

## Treatment

We calculated treatment outcome rates directly from
the raw counts provided by WHO. Treatment success
is calculated as the number cured or completing treatment,
pooled across new, retreatment and MDR cohorts, divided by
the size of those cohorts. Because data pertain to annual cohorts
of persons underoing treatment, times are offset by
0.5 of a year to sit at mid-year. The proportion of unsuccessful outcomes resulting in death
is calculated as deaths divided by deaths plus failure, default and
loss to follow-up, pooled across the same cohorts as for
the treatment success calculations. The probability of background death during a course of
treatment was calculated as $1 - \exp(-\delta \mu)$,
where $\delta$ is the "treatment duration" parameter and $\mu$ is
the age-specific background mortality rate. The remaining
proportion was split according to the treatment success
rate and the proportion of unsuccessful outcomes that are
deaths. Background deaths already counted are subtracted from
the death proportion, such that only the additional deaths
during treatment in excess of background mortality
are attributed to the TB-related mortality transition.
The remaining proportion of the unsuccessful fraction
after treatment-related deaths have been subtracted
was considered as relapse. Treatment success was calculated as
the complement of treatment-related death plus relapse.

People on treatment leave the treatment compartment through one of
the three possible outcomes (success, relapse and death),
with the scaling rates interpolated over calendar time.
Treatment success returns people to the recovered compartment.
Relapse returns them to subclinical, low-infectious active TB.
As for non-TB-related deaths, each death during treatment is
replaced by an _Mtb_-naive birth into the youngest age group.

Each treatment outcome proportion is converted to a
competing hazard by dividing by the treatment duration.

# Active case finding

Active case finding screens is assumed to screen all people aged
"10" years and over, and transitions detected
TB cases onto treatment. Unlike routine detection, this
includes subclinical disease.

The peak screening rate is $-\ln(1 - c)$, where $c$ is
the "active case finding coverage" parameter. This converts annual coverage into a
hazard over time. Detection then scales that rate by a
stratum-specific Xpert Ultra sensitivity: "active case finding sensitivity for high-infectious TB"
for the high infectiousness stratum and "active case finding sensitivity for low-infectious TB"
for the low infectiousness stratum. The low-infectious rate is
further multiplied by the "proportion of low-infectious TB that is bacteriologically positive" to account for
TB cases that are extrapulmonary or otherwise not detectable.
These sensitivities are taken from Zifodya et al. (Cochrane
Database of Systematic Reviews, 2021) on Xpert Ultra for
pulmonary TB in adults; the high-infectious value is the
smear-positive estimate and the low-infectious value is the
smear-negative estimate (applied to the bacteriologically
detectable fraction of that stratum).

The rate is zero until the "active case finding start year" time, then follows a
cosine-smoothed scale-up over "active case finding scale-up time" years
to its peak rate as defined above. It then remains at this peak value
throughout the "active case finding duration" period, and declines back to
zero over a further "active case finding scale-up time" years.

# Model outputs

| Indicator            | Definition                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
|:---------------------|:-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Incidence            | Incidence is the calculated as the total number of persons progressing from incipient infection to active disease.                                                                                                                                                                                                                                                                                                                                           |
| Prevalence           | TB prevalence is calculated as the total population in the compartments: active, treatment.                                                                                                                                                                                                                                                                                                                                                                  |
| Pulmonary prevalence | For bacteriologically-confirmed pulmonary tuberculosis, the numerator comprises both active disease states of the high infectiousness stratum, a fraction of the low infectiousness stratum given by "proportion of low-infectious TB that is bacteriologically positive", and all persons under treatment. Clinical status does not affect this calculation. All modelled age groups are included for this calculation (unlike for the calibration target). |
| Treatment prevalence | This is the population in the treatment compartment, summed within each modelled age group.                                                                                                                                                                                                                                                                                                                                                                  |
| Notifications        | Notifications are calculated from both routine detection as well as the active case finding intervention.                                                                                                                                                                                                                                                                                                                                                    |
| TB deaths            | TB-related deaths are caculated from both TB natural mortality prior to detection, along with treatment-related deaths.                                                                                                                                                                                                                                                                                                                                      |

: {tbl-colwidths="[30,70]"}

## Mapping to output age groups

Each modelled age group is split across output age groups
according to the share of its population that overlaps each
output group, using single-year population counts. Age-stratified outputs are reallocated from modelled age
groups to requested output age groups using the population
overlap fractions. These fractions are calculated from
1^st^ January WPP counts for the calendar year of each
(often mid-year) output time. Age-stratified outputs are regrouped to the requested age bands.
The WPP age-structure mapping is used to join each mid-year output
to that year's 1^st^ January population.

# Calibration
## Likelihood construction

The log-likelihood is the sum of seven contributions,
which are each taken as independent:
the adult prevalence of _Mtb_ infection, case notifications, TB
deaths, adult bacteriologically-confirmed prevalence, the decline in
prevalence between the two prevalence surveys, the proportion of
prevalent disease that is highly infectious, and the Canberra distance
between the modelled mixing matrix and a synthetic contact matrix.

Two error models are applied to the epidemiological targets. Counts and
ratios are compared on the log scale using a normal distribution,
as $\log \hat{y} \sim \mathcal{N}(\log y, \sigma_{c})$ with $\sigma_{c}$ of
0.1, so that the discrepancy scales with the magnitude of
the target. Proportions are compared on the log-odds scale,
also using a normal distribution,
as $\mathrm{logit}(\hat{p}) \sim \mathcal{N}(\mathrm{logit}(p), \sigma_{p})$
with $\sigma_{p}$ of 0.2, thereby respecting their domain
of $[0, 1]$. In both cases the transformed target provides the mean of
the distribution, which the transformed modelled value is evaluated against.

The mixing-matrix contribution uses a third error model: the Canberra
distance from the synthetic matrix is compared to zero under a normal
distribution whose standard deviation, the "mixing matrix distance standard deviation", is
itself estimated. A uniform prior on this scale allows the weight of the
mixing target adjust to the data, while ensuring that its range
that remains comparable to the epidemiological contributions.

For targets that comprise observations over multiple years,
the log-density is averaged over the years for which it is available,
so that each epidemiological series carries comparable weight
irrespective of the number of observations it comprises.

## Target calculations

### Prevalence of infection

The proportion of adults ever infected with _Mtb_ was compared
against the interferon-gamma release assay survey of people aged
15 years and over reported by Marks et al.
(_International Journal of Tuberculosis and Lung Disease_).

The corresponding modelled quantity is everyone not previously
infected with _Mtb_, which is represented by
all modelled compartments other than _Mtb_-naive.
That is, the incipient, contained, cleared, active, treatment, recovered states among adults,
divided by the adult population at the time of the survey.

As for other proportion targets, this quantity was compared on
the log-odds scale, with a standard deviation of 0.2.

### Notifications

Modelled case detections were compared against case notification counts
obtained from the Vietnam National Tuberculosis Program. These are
reported by calendar year, and so are offset by
0.5 of a year to sit at mid-year.
The model is solved in whole years, then linearly interpolated
to those mid-year points for comparison.

Being counts, notifications are compared on the log scale with a
standard deviation of 0.1, thereby relating the error
to the magnitude of the target, rather than using an absolute value.
The log-density is averaged rather than summed over the years of data, so
that this multi-year series contributes comparable weight to the likelihood
as do the single-point targets.

### Deaths

WHO estimates of TB deaths with and without HIV are summed
to create a single mortality series. Burden estimates are offset by 0.5 of a year
to sit at mid-year. Deaths occurring in the community and during treatment are
summed for comparison.

As for notifications, these counts are
compared on the log scale with a standard deviation of 0.1,
and averaged over the years for which estimates are available.

### Pulmonary prevalence

Prevalence is calculated to approximate the quantity ascertained by a
bacteriologically-confirmed prevalence survey, and so is restricted to
adults, taken here as those aged 15 years and over.
Three groups contribute to the numerator: all persons with active disease
in the high infectiousness stratum, a proportion of persons in the low
infectiousness stratum given by the "proportion of low-infectious TB that is bacteriologically positive", and
everyone currently receiving treatment. Clinical status does not
enter this calculation, with subclinical and clinical disease contributing
on the same basis. The denominator is the total
adult population at the same time point. Modelled adult prevalence of bacteriologically-confirmed pulmonary TB was
compared against the most recent (second) Vietnamese national prevalence survey
(PLOS One). This study reports prevalent cases per 100,000 population
as a proportion of the adult population. Being a proportion,
this quantity was compared on the log-odds scale with
a standard deviation of 0.2.

The two survey rounds reported and compared in Nguyen et al.
(Emerging Infectious Diseases) are used to target the decline in
prevalence rather than absolute values.
The ratio of the later to the earlier adult pulmonary prevalence estimate
is taken, such that this rate of decline target constrains the trend in
a single quantity over time, without reference to the absolute prevalence value.
The ratio is compared on the log scale with a
 standard deviation of 0.1.

The proportion of prevalent adult TB that is highly infectious was
compared against the equivalent proportion from the second Vietnamese
national prevalence survey.
The numerator is the high infectiousness stratum of the active
compartment and the denominator is total adult prevalence, as defined
above. This target therefore constrains how prevalent disease is
distributed across the infectiousness strata, without
constraining the overall size of the prevalent pool.
Being a proportion, this quantity is compared on the log-odds scale with
a standard deviation of 0.2.

### Mixing matrix

The modelled age-mixing matrix in 2025 was compared
against a synthetic contact matrix for VNM, generated by projecting
POLYMOD contact patterns onto the country's age structure using the
`conmat` R package. Both matrices are normalised by their spectral
radius before comparison, so that only the relative pattern of
age-to-age mixing is targeted.

The discrepancy is summarised by the Canberra distance, which gives
comparable weight to low- and high-contact cells. This distance is
treated as a residual around zero,
$d \sim \mathcal{N}(0, \sigma_{m})$, where $\sigma_{m}$ is the
"mixing matrix distance standard deviation". Unlike the fixed error scales used for the
epidemiological targets, $\sigma_{m}$ is estimated during calibration
under a uniform prior. This restricted range stops the mixing penalty from becoming
arbitrarily tight or from being ignored entirely. Within that range,
$\sigma_{m}$ tracks how large a discrepancy is needed to reconcile the
synthetic contact matrix with the epidemiological data.

The Canberra distance is the sum over corresponding cells of the
absolute difference divided by the sum of the absolute values,
$$
d = \sum_{i,j}
\frac{|x_{ij} - y_{ij}|}{|x_{ij}| + |y_{ij}| + \varepsilon}
$$
with $\varepsilon =$ $1 \times 10^{-10}$ to avoid division by zero.
Because each term represents a relative discrepancy, low-contact cells
contribute comparably to high-contact cells.

## Fixed parameters

In [3]:
fixed_params = {k: v for k, v in BASE_PARAMS.items() if k not in PARAM_BOUNDS}
build_fixed_params_table(fixed_params)

                                                       value
Parameter
relative susceptibility of the never-infected              1
relative infectiousness of subclinical TB                0.5
relative infectiousness of low-infectious TB             0.4
progression rate under 5 years                           2.4
progression rate ages 5 to 15                              2
progression rate ages 15 and over                        0.1
proportion of progressions that are high-infect...       0.2
containment rate under 5 years                           4.4
containment rate ages 5 to 15                            4.4
containment rate ages 15 and over                          2
rate of clinical regression                                1
rate of infectiousness decrease                            1
TB mortality rate for high-infectious disease          0.389
TB mortality rate for low-infectious disease           0.025
self-recovery rate                                       0.4
treatment duration                                       0.5
seeding peak year                                       1830
seeding duration                                          10
seeding peak rate                                       0.01
active case finding coverage                               0
active case finding sensitivity for high-infect...      0.96
active case finding sensitivity for low-infecti...     0.775
active case finding start year                          2027
active case finding duration                               5
active case finding scale-up time                          1
proportion of low-infectious TB that is bacteri...  0.666667

## Prior ranges

Pass the dict of prior bounds to show.

In [4]:
build_prior_ranges_table(PARAM_BOUNDS)

                                                    lower upper
Parameter
raw transmission rate                                   8    20
background mixing                                   0.001  0.02
assortative mixing spread                               2    15
parent-child mixing strength                         0.05     1
relative susceptibility of contained infection        0.2   0.8
relative susceptibility of cleared or recovered...    0.2   0.8
relative susceptibility of never-infected children    0.2   0.8
breakdown rate                                       0.01   0.5
clearance rate                                       0.01   0.1
rate of clinical progression                          0.5     5
rate of infectiousness increase                       0.1     1
current detection rate                                0.5   1.5
relative detection rate in 2007 compared to cur...    0.6   0.9
relative detection rate in 1986 compared to 2007      0.6   0.9
COVID-19-related detection reduction                  0.4   0.8
mixing matrix distance standard deviation               5    20